name: undercover
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_0
  - alphashape=1.3.1=pyh44b312d_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - attrs=24.2.0=py38hd43f75c_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=openblas
  - blosc=1.21.6=he3a29bc_0
  - boost-cpp=1.82.0=hb8fdbf2_2
  - branca=0.6.0=py38hd43f75c_0
  - brotli=1.0.9=h998d150_9
  - brotli-bin=1.0.9=h998d150_9
  - brotli-python=1.0.9=py38h419075a_8
  - bzip2=1.0.8=h998d150_6
  - c-ares=1.34.5=ha6cfe40_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=hd97bfd3_0
  - certifi=2024.8.30=py38hd43f75c_0
  - cfitsio=3.470=hb113702_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py38hd43f75c_0
  - click-log=0.4.0=pyhd8ed1ab_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contextily=1.1.0=pyhd8ed1ab_0
  - contourpy=1.0.5=py38hb8fdbf2_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py38h419075a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.1=h419075a_0
  - fiona=1.9.5=py38hfb1e5ee_0
  - folium=0.14.0=py38hd43f75c_0
  - fontconfig=2.14.1=h652894d_2
  - fonttools=4.51.0=py38h998d150_0
  - freetype=2.13.3=h6df46f4_0
  - freexl=1.0.6=h2f4d8fa_0
  - gdal=3.6.2=py38h9cfbf26_3
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopandas=0.12.2=py38hd43f75c_0
  - geopandas-base=0.12.2=py38hd43f75c_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.8.0=h22f4aa5_1
  - geotiff=1.7.0=haef6a04_1
  - giflib=5.2.2=h998d150_0
  - glib=2.84.2=h419075a_0
  - glib-tools=2.84.2=h419075a_0
  - hdf4=4.2.13=h96bad59_4
  - hdf5=1.12.1=h2117f30_3
  - icu=73.1=h419075a_0
  - idna=3.7=py38hd43f75c_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.0=py38hd43f75c_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py38hd43f75c_0
  - joblib=1.4.2=py38hd43f75c_0
  - jpeg=9f=h31cb85b_0
  - json-c=0.16=h998d150_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - kealib=1.5.0=h1b42569_1
  - kiwisolver=1.4.4=py38h419075a_0
  - krb5=1.20.1=h2e2fba8_1
  - lcms2=2.16=hd2bd712_0
  - ld_impl_linux-aarch64=2.44=h9df1782_2
  - lerc=3.0=h22f4aa5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=hda0696e_2
  - libbrotlicommon=1.0.9=h998d150_9
  - libbrotlidec=1.0.9=h998d150_9
  - libbrotlienc=1.0.9=h998d150_9
  - libcblas=3.9.0=5_h6783c1e_netlib
  - libcurl=8.15.0=h2e08ae6_0
  - libdeflate=1.17=h998d150_1
  - libedit=3.1.20230828=h998d150_0
  - libev=4.33=hfd63f10_1
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=he277a41_7
  - libgcc-ng=15.2.0=he9431aa_7
  - libgdal=3.6.2=h2dbb9bc_3
  - libgfortran-ng=11.2.0=h6e398d7_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h4c1cdc3_0
  - libgomp=15.2.0=he277a41_7
  - libiconv=1.16=h998d150_3
  - libkml=1.3.0=hadc4260_7
  - liblapack=3.9.0=5_h6783c1e_netlib
  - liblzma=5.8.1=h86ecc28_2
  - liblzma-devel=5.8.1=h86ecc28_2
  - libnetcdf=4.8.1=hff16709_4
  - libnghttp2=1.57.0=hb788212_0
  - libnsl=2.0.1=h86ecc28_1
  - libopenblas=0.3.30=h90745d9_0
  - libpng=1.6.50=h01b5ae2_0
  - libpq=12.20=h6ac735f_0
  - libsodium=1.0.18=hb9de7d4_1
  - libspatialindex=1.9.3=h7c1a80f_0
  - libspatialite=4.3.0a=h3693699_23
  - libsqlite=3.46.0=hf51ef55_0
  - libssh2=1.11.1=hfa2bbb0_0
  - libstdcxx=15.2.0=h3f4de04_7
  - libstdcxx-ng=15.2.0=hf1166c9_7
  - libtiff=4.5.1=h419075a_0
  - libuuid=1.41.5=h998d150_0
  - libwebp-base=1.3.2=h998d150_1
  - libxcb=1.17.0=hf66535e_0
  - libxml2=2.10.4=h6097fa9_2
  - libzip=1.8.0=h654c02d_1
  - libzlib=1.2.13=h68df207_6
  - lz4-c=1.9.4=h419075a_1
  - mapclassify=2.5.0=py38hd43f75c_0
  - markupsafe=2.1.3=py38h998d150_0
  - matplotlib=3.3.3=py38h2063c64_0
  - matplotlib-base=3.3.3=py38h52aeb00_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - ncurses=6.5=ha32ae93_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py38hd43f75c_0
  - nspr=4.37=he858ca9_0
  - nss=3.89.1=h419075a_0
  - numpy=1.22.4=py38h9138613_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.5.2=ha2c532c_0
  - openssl=3.5.4=h8e36d6e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.2.3=py38hfba8312_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.42=hcfaa891_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38h127099d_0
  - pixman=0.46.4=h419075a_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.7.0=py38hd43f75c_0
  - poppler=22.12.0=h483b0c5_3
  - poppler-data=0.4.12=hd43f75c_0
  - proj=6.2.1=h465d533_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=5.9.0=py38h998d150_0
  - pthread-stubs=0.3=hfd63f10_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py38hd43f75c_0
  - pyproj=2.6.1.post1=py38hc41e337_1
  - pysocks=1.7.1=py38hd43f75c_0
  - python=3.8.12=h47f6e27_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.1=py38hd43f75c_0
  - pyzmq=25.1.2=py38h419075a_0
  - qhull=2020.2=hb8fdbf2_2
  - rasterio=1.3.10=py38h1a1623f_0
  - readline=8.2=h8382b9d_2
  - requests=2.32.3=py38hd43f75c_0
  - rtree=1.0.1=py38hd43f75c_0
  - scikit-learn=1.3.0=py38hfb1e5ee_1
  - scipy=1.10.1=py38h7caaa05_1
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - snuggs=1.4.7=pyhd8ed1ab_1
  - sqlite=3.46.0=hdc7ab3c_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38h8c3297f_0
  - threadpoolctl=3.5.0=py38ha5ee653_0
  - tiledb=2.3.3=h3849020_3
  - tk=8.6.13=h194ca79_0
  - tornado=6.4.1=py38h998d150_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trimesh=4.5.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py38h998d150_0
  - uriparser=0.9.8=ha6cfe40_0
  - urllib3=2.2.3=py38hd43f75c_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xerces-c=3.2.4=h419075a_1
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-libxext=1.3.6=hf66535e_0
  - xorg-libxrender=0.9.12=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xyzservices=2022.9.0=py38hd43f75c_1
  - xz=5.8.1=h2dbfc1b_2
  - xz-gpl-tools=5.8.1=h2dbfc1b_2
  - xz-tools=5.8.1=h86ecc28_2
  - zeromq=4.3.5=h2f0025b_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h68df207_6
  - zstd=1.5.6=h6a09583_0
  - pip:
      - pip==25.0.1
      - setuptools==75.3.2
      - shapely==1.7.0
prefix: /opt/conda/envs/undercover
