name: undercover
channels:
  - conda-forge
  - defaults
dependencies:
  - contextily=1.1.0
  - geopandas=0.10.2
  - matplotlib
  - numpy=1.19.2
  - pandas=1.2.3
  - pillow=8.1.2
  - python=3.8.2
  - seaborn-base=0.11.1
  - shapely=1.7.0
  - pip:
      - alphashape==1.3.1
