name: undercover
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - affine=2.3.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - blas=1.0=mkl
  - branca=0.7.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.14.12=h8948797_3
  - cartopy=0.17.0=py38h423102d_1009
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.14.4=py38ha312104_0
  - cfgrib=0.9.8.1=py_0
  - cfitsio=3.470=hb7c8383_2
  - chardet=4.0.0=py38h578d9bd_1
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=1.6.0=py_0
  - contextily=1.1.0=pyhd8ed1ab_0
  - cryptography=3.2.1=py38h7699a38_0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py38_0
  - cython=0.29.17=py38h950e882_0
  - cytoolz=0.11.0=py38h25fe258_1
  - dask-core=2021.3.1=pyhd8ed1ab_0
  - datefinder=0.7.1=pyh9f0ad1d_0
  - dateparser=1.1.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - descartes=1.1.0=py_4
  - earthpy=0.9.2=py_0
  - eccodes=2.12.3=h4fa793d_1
  - expat=2.3.0=h2531618_2
  - fiona=1.8.13=py38h900e953_0
  - folium=0.18.0=pyhd8ed1ab_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - freexl=1.0.6=h27cfd23_0
  - fsspec=0.8.7=pyhd8ed1ab_0
  - gdal=3.0.2=py38hbb2a789_0
  - geographiclib=1.50=py_0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geoplot=0.5.1=pyhd8ed1ab_0
  - geopy=2.1.0=pyhd3deb0d_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.5.1=h21e8280_1
  - giflib=5.1.4=h14c3975_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.22.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.0=py38_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h1bed415_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyterthemes=0.20.0=py_1
  - kealib=1.4.7=hd0c454d_6
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.16.4=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lesscpy=0.15.0=pyhd8ed1ab_0
  - libaec=1.0.4=he1b5a44_1
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.67.0=h20c2e04_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=3.0.2=h27ab9cc_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=4.3.0a=h793db0d_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=20.1.8=h4922eb0_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.1.2=h14c3975_0
  - mapclassify=2.4.2=pyhd8ed1ab_0
  - markupsafe=3.0.1=pyhe1237c8_1
  - matplotlib=3.3.3=py38h578d9bd_0
  - matplotlib-base=3.3.3=py38h5c7f4ab_0
  - mercantile=1.1.6=pyh9f0ad1d_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - munch=2.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1w=h7f8727e_0
  - owslib=0.23.0=pyhd8ed1ab_0
  - pandas=1.2.3=py38ha9443f7_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.1.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - ply=3.11=py_1
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.10=h06a4308_0
  - postgresql=11.2=h20c2e04_0
  - proj=6.2.1=haa6030c_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=pyh9f0ad1d_2
  - pyepsg=0.4.0=py_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pygrib=2.0.5=py38hb6c87f9_1
  - pykdtree=1.3.4=py38h0b5ebd8_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyproj=2.4.2.post1=py38h12732c1_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.2=h191fe78_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38hab2c0dc_3
  - pyyaml=5.3.1=py38h8df0ef7_1
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - rasterio=1.1.2=py38h900e953_0
  - readline=7.0=h7b6447c_5
  - regex=2022.3.15=py38h7f8727e_0
  - requests=2.25.1=pyhd3deb0d_0
  - rtree=1.2.0=py38h02d302b_0
  - scikit-image=0.16.2=py38hb3f55d8_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.2=py38h91f5cce_0
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - setuptools=52.0.0=py38h06a4308_0
  - shapely=1.7.0=py38h786ee0b_1
  - simplejson=3.17.2=py38h1e0a361_1
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.4=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2018.0.5=h6bb024c_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tiledb=1.6.3=h1fb8f14_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzlocal=2.1=py38h06a4308_1
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xarray=0.15.0=py_0
  - xerces-c=3.2.3=h780794e_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
      - gpd-lite-toolbox==0.0.0.post27
      - rasterstats==0.20.0
