name: undercover
channels:
  - conda-forge
  - defaults
dependencies:
  - contextily
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pillow
  - python
  - seaborn-base
  - shapely
  - pip:
      - alphashape
